services:
  api:
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
